services:
  mtproto-proxy:
    #image: ghcr.io/rumkit/mtproto-proxy:latest
    build:
      context: .
    container_name: mtproxy
    volumes:
      - proxy-config:/data
    restart: unless-stopped
    ports:
      - 14443:443/udp
      - 14443:443/tcp
volumes:
  proxy-config:
